# Generated by Django 6.0.1 on 2026-02-03 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.PositiveIntegerField(help_text='Número de identificação na igreja', unique=True, verbose_name='Nº da Ficha')),
                ('nome_completo', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('naturalidade', models.CharField(blank=True, help_text='Cidade/Estado', max_length=100, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('orgao_expedidor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão Exp.')),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('VIUVO', 'Viúvo(a)'), ('DIVORCIADO', 'Divorciado(a)')], max_length=20)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('nome_pai', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Mãe')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=20, verbose_name='Nº')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(default='RJ', max_length=2, verbose_name='UF')),
                ('telefone', models.CharField(max_length=20, verbose_name='Celular/WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_batismo_aguas', models.DateField(blank=True, null=True, verbose_name='Batismo nas Águas')),
                ('data_batismo_espirito', models.DateField(blank=True, null=True, verbose_name='Batismo no Espírito Santo')),
                ('cargo', models.CharField(choices=[('MEMBRO', 'Membro'), ('AUXILIAR', 'Auxiliar'), ('DIACONO', 'Diácono'), ('PRESBITERO', 'Presbítero'), ('EVANGELISTA', 'Evangelista'), ('PASTOR', 'Pastor'), ('OUTRO', 'Outro')], default='MEMBRO', max_length=20)),
                ('cargo_outro', models.CharField(blank=True, help_text="Preencher se escolheu 'Outro'", max_length=50, null=True)),
                ('igreja_procedencia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Igreja de Procedência')),
                ('congregacao', models.CharField(choices=[('Matriz em Piabetá', 'Matriz em Piabetá'), ('Jardim Prainha', 'Jardim Prainha'), ('Jardim Ana Beatriz', 'Jardim Ana Beatriz'), ('Parque Santana', 'Parque Santana'), ('Parque Veneza', 'Parque Veneza'), ('Rua das Mangueiras', 'Rua das Mangueiras'), ('Saracuruna', 'Saracuruna'), ('Avenida Mauá', 'Avenida Mauá'), ('Fragoso', 'Fragoso'), ('Meio da Serra', 'Meio da Serra'), ('Pau Grande', 'Pau Grande'), ('Jardim Nazareno', 'Jardim Nazareno'), ('Parque Sayonara', 'Parque Sayonara'), ('Vila Serrana / Ilha', 'Vila Serrana / Ilha'), ('Cachoeira Grande', 'Cachoeira Grande'), ('Boa Esperança', 'Boa Esperança'), ('Figueira Conceição', 'Figueira Conceição'), ('Rio do Ouro', 'Rio do Ouro'), ('Rio Novo', 'Rio Novo'), ('Suruí', 'Suruí'), ('Cidade Naval', 'Cidade Naval'), ('Figueira Magé', 'Figueira Magé'), ('Itambi / Mauá', 'Itambi / Mauá'), ('Leque Azul', 'Leque Azul'), ('Santa Dalila', 'Santa Dalila'), ('Ypiranga', 'Ypiranga'), ('Paraíso do Góia', 'Paraíso do Góia'), ('Bacaxá / Vila Canaã', 'Bacaxá / Vila Canaã'), ('Bananeiras / Água', 'Bananeiras / Água'), ('Fazendinha Branca', 'Fazendinha Branca'), ('Bonsucesso', 'Bonsucesso'), ('Praia Seca / Raia', 'Praia Seca / Raia'), ('Macaé / Itatiquara', 'Macaé / Itatiquara'), ('Parque Cidade Luz', 'Parque Cidade Luz'), ('Betel / Bereia', 'Betel / Bereia'), ('Filadelfia / Imburi', 'Filadelfia / Imburi'), ('Eldorado', 'Eldorado'), ('Parque Nova Campos', 'Parque Nova Campos'), ('Parque Prazeres', 'Parque Prazeres'), ('Vila Menezes', 'Vila Menezes')], default='Matriz em Piabetá', max_length=100, verbose_name='Congregação')),
                ('nome_conjuge', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Cônjuge')),
                ('anotacoes', models.TextField(blank=True, null=True, verbose_name='Anotações')),
                ('aceite_termos', models.BooleanField(default=False, verbose_name='Aceito os termos de uso de dados')),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='membros.membro')),
            ],
        ),
    ]
