# Generated by Django 6.0.1 on 2026-02-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_membros/', verbose_name='Foto do Membro'),
        ),
    ]
