# Generated by Django 6.0.1 on 2026-02-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0003_remove_membro_ativo_membro_situacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='orgao_expedidor',
        ),
    ]
