# Generated by Django 6.0.1 on 2026-02-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0004_remove_membro_orgao_expedidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='data_batismo_espirito',
        ),
    ]
