# Generated by Django 6.0.1 on 2026-02-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0005_remove_membro_data_batismo_espirito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='numero_ficha',
            field=models.PositiveIntegerField(blank=True, help_text='Gerado automaticamente pelo sistema', null=True, unique=True, verbose_name='Nº da Ficha'),
        ),
    ]
