# Generated by Django 6.0.1 on 2026-02-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0006_alter_membro_numero_ficha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='aceite_termos',
        ),
    ]
