# Generated by Django 6.0.1 on 2026-02-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0007_remove_membro_aceite_termos'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='numero_ficha_antiga',
            field=models.CharField(blank=True, help_text='Preencher manualmente caso exista', max_length=20, null=True, verbose_name='Nº Ficha Antiga'),
        ),
    ]
