# Generated by Django 6.0.1 on 2026-02-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0008_membro_numero_ficha_antiga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='numero_ficha_antiga',
            field=models.CharField(blank=True, help_text='Máx. 5 dígitos', max_length=5, null=True, verbose_name='Nº Ficha Antiga'),
        ),
    ]
