# Generated by Django 6.0.1 on 2026-02-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0009_alter_membro_numero_ficha_antiga'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='historico_eclesiastico',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico Eclesiástico'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='congregacao',
            field=models.CharField(choices=[('Matriz em Piabetá', 'Matriz em Piabetá'), ('Jardim Prainha', 'Jardim Prainha'), ('Jardim Ana Beatriz', 'Jardim Ana Beatriz'), ('Parque Santana', 'Parque Santana'), ('Parque Veneza', 'Parque Veneza'), ('Rua das Mangueiras', 'Rua das Mangueiras'), ('Saracuruna', 'Saracuruna'), ('Avenida Mauá', 'Avenida Mauá'), ('Fragoso', 'Fragoso'), ('Meio da Serra', 'Meio da Serra'), ('Pau Grande', 'Pau Grande'), ('Jardim Nazareno', 'Jardim Nazareno'), ('Parque Sayonara', 'Parque Sayonara'), ('Vila Serrana', 'Vila Serrana'), ('Ilha', 'Ilha'), ('Cachoeira Grande', 'Cachoeira Grande'), ('Boa Esperança', 'Boa Esperança'), ('Figueira Conceição', 'Figueira Conceição'), ('Rio do Ouro', 'Rio do Ouro'), ('Rio Novo', 'Rio Novo'), ('Suruí', 'Suruí'), ('Cidade Naval', 'Cidade Naval'), ('Figueira Magé', 'Figueira Magé'), ('Itambi', 'Itambi'), ('Mauá', 'Mauá'), ('Leque Azul', 'Leque Azul'), ('Santa Dalila', 'Santa Dalila'), ('Ypiranga', 'Ypiranga'), ('Paraíso do Góia', 'Paraíso do Góia'), ('Bacaxá', 'Bacaxá'), ('Vila Canaã', 'Vila Canaã'), ('Bananeiras', 'Bananeiras'), ('Água Branca', 'Água Branca'), ('Fazendinha', 'Fazendinha'), ('Bonsucesso', 'Bonsucesso'), ('Praia Seca', 'Praia Seca'), ('Raia', 'Raia'), ('Macaé', 'Macaé'), ('Itatiquara', 'Itatiquara'), ('Parque Cidade Luz', 'Parque Cidade Luz'), ('Betel', 'Betel'), ('Bereia', 'Bereia'), ('Filadelfia', 'Filadelfia'), ('Imburi', 'Imburi'), ('Eldorado', 'Eldorado'), ('Parque Nova Campos', 'Parque Nova Campos'), ('Parque Prazeres', 'Parque Prazeres'), ('Vila Menezes', 'Vila Menezes')], default='Matriz em Piabetá', max_length=100, verbose_name='Congregação'),
        ),
    ]
